### ISSUE TITLE
Removing punctuation for initials and abbreviations

### ISSUE THREAD

**Issue by ezgranet** [alex-ball/biblatex-oxref#11]
Is there a way to remove all punctuation (ie full stops), particularly in author's names (as is recommended by eg OSCOLA)?  I am using the `oxnotes` style, but would like names to appear in the way they do in, for example, Cambridge's recommended internal style, with spaces following initials.  In other words:  H R W Wade rather than H.R.W. Wade.  

Similarly, is it possible to remove punctuation when using the `trad` variation? For example, removing any full stop after ibid. (as is recommended when choosing to use ibid with OSCOLA)?
  This is particularly the case with 'eds.', which I would very much like to be 'eds'.

I apologise if this is in the documentation and I missed it—thanks very much for this excellent package!

**Comment by alex-ball** [comment]
I'm glad you are finding this style useful.

I try to make sure I preserve as much flexibility as possible from the base package, since the nature of Oxref is not to be a rigid implementation but a closer starting point for a certain class of styles. So the answers you need are not in my manual but in the one for biblatex itself. To save you picking through all 338 pages of it, the dot after initials is defined in `\bibinitperiod` and the bib strings like "ibidem" and "editors" can be changed using `\DefineBibliographyStrings`. Here is a minimal working example:

```tex
\documentclass[varwidth=67ex]{standalone}
\usepackage[style=oxnotes-trad1,giveninits=true]{biblatex}
\renewcommand{\bibinitperiod}{}
\DefineBibliographyStrings{english}{
  editor           = {ed},
  editors          = {eds},
  ibidem           = {ibid},
  opcit            = {op\space cit},
  loccit           = {loc\space cit},
  confer           = {cf},
  sequens          = {sq},
  sequentes        = {sqq},
  passim           = {pass},
}

\addbibresource{biblatex-examples.bib}

\begin{document}
\setlength{\parskip}{0.5em}
\cite[12]{cicero}.\par
\cite[12]{cicero}.\par
\cite[12]{matuz:doody}.\par
\cite[13]{matuz:doody}.

\printbibliography
\end{document}
```

![LaTeX output](https://user-images.githubusercontent.com/1890395/85844238-4d6c2100-b79a-11ea-8c6e-41f674e3105c.png)

**Comment by ezgranet** [comment]
Thank you so much!!
