### ISSUE TITLE
Unwanted 'from in' when a work is reprinted from an incollection

### ISSUE THREAD

**Issue by ciandorr** [alex-ball/biblatex-oxref#15]
Hi - I hope you won't feel like I'm spamming you with small issues, but I was so impressed by how quickly you fixed the last one that I thought I'd tell you about another small thing that I'm not sure how to fix.  My bibliography contains many entries that are in a volume someone's collected papers but reprinted from some other volume, such as the following:

@inbook{LewisSI,
	author = {David K. Lewis},
	crossref = {LewisPP2},
	origdate = {1976},
	pages = {55--77},
	related = {LewisSIorig},
	relatedtype = {reprintfrom},
	title = {Survival and Identity}}

@book{LewisPP2,
	author = {David K. Lewis},
	publisher = OUP,
	title = {Philosophical Papers},
	volume = 2,
	year = 1986}

@incollection{LewisSIorig,
	author = {Lewis, David K.},
	booktitle = {The Identities of Persons},
	editor = {Amelie Oksenberg Rorty},
	pages = {17-40},
	title = {Survival and Identity},
	year = {1976}}

Here's what I get in my bibliography, using oxyear (notice the lovely way the backref page references are grouped at the end - thanks for that):

![screenshot](https://user-images.githubusercontent.com/2462683/104062090-cfb4b380-51c7-11eb-8932-007db8381458.jpg)

As you can see, it says 'from in' which surely isn't what we want.  I don't know if any of the Oxford examples cover this case but I would favour getting rid of the 'in' in the case and just having 'from'.  But I'm not sure how to do this without making of the 'in's disappear even for main entries, which wouldn't be good.

**Comment by alex-ball** [comment]
(`reprintfrom` should actually be ". From" rather than ", from". It looks like it broke around v1.0 and I hadn't noticed until now.)

Okay, the "from" comes from the "reprintfrom" relation, and the "in" is part of the "@incollection" driver; it looks odd because the repeated author and title have been automatically deleted from the "@incollection" entry. In fairness, it is not entirely ungrammatical, though in everyday speech you'd more normally see "from inside", "from within", or "from [something] in".

You can work around the issue for now with a semantically dodgy use of a "@collection" entry:

```bibtex
@collection{LewisSIorig,
title = {The Identities of Persons},
editor = {Amelie Oksenberg Rorty},
publisher = {University of California Press},
pages = {17-40},
year = {1976}}
```

I expect the approach to take would be to wrap the `\usebibmacro{in:}` line in a test such that it is only printed if the entry has a `author` or a `title` (these are cleared by the `related:reprintfrom` bibmacro).

**Comment by alex-ball** [comment]
Come to think of it, a more attractive solution might be to override the related string, for example:

```
related = {LewisSIorig},
relatedtype = {reprintfrom},
relatedstring = {originally published},
```

which would give you a more satisfactory "originally published in Amelie Oksenberg Rorty (ed.)".

**Comment by ciandorr** [comment]
Thanks!  That’s clever and will do the job.
