### ISSUE TITLE
uniquename 

### ISSUE THREAD

**Issue by wujastyk** [alex-ball/biblatex-oxref#17]
Dear Alex,

My wife and I have the same initial and surname and we work in adjacent fields.  So I have to think about `uniquename`.  The oxyear manual says

> If different authors have the same surname, they are distiguished by their initial.

but that's not enough.  We have to have our first names spelled out, in citations and in the bibliography.

Using `\ExecuteBibliographyOptions{uniquename=full}` almost works, but the first names are still not shown in the bibliography.

I realize I'm trying to do something that Hart doesn't seem to recognize.  But I wondered whether oxref could be encouraged to do this more in the manner of plain biblatex.

(There's a tiny typo on p. 9 of the oxyear doc: distiguished.)

MWE attached.

Best wishes,
Dominik

[kkkk.zip](https://github.com/alex-ball/biblatex-oxref/files/6488502/kkkk.zip)

**Comment by alex-ball** [comment]
Dear Dominik,

Thanks for spotting the typo.

Oxref behaves *exactly* like plain biblatex. The issue only arises because oxyear executes the `giveninits` option at a global level.

You can switch it back off again with the `giveninits=false` option, which you can give globally or on a per-type, per-entry, per-namelist or per-name basis.

I would recommend you switch it off at the name level. In the affected entries, specify your names in your .bib file in the following manner:

```
author = {given=Dominik, family=Wujastyk, giveninits=false},
```

All the best,
Alex.

**Comment by wujastyk** [comment]
Thank you!!!
