### ISSUE TITLE
Spans of years in multi-volume works

### ISSUE THREAD

**Issue by wujastyk** [alex-ball/biblatex-oxref#19]
When the BibLaTeX `date` field has a span of dates, e.g., `1935/1938`, as in 

```
@MvBook{spen-1935,
  author           = {Walter George Spencer},
  date             = {1935/1938},
  location         = {Cambridge, MA; London},
  publisher        = {Harvard University Press; William Heinemann},
  title            = {Celsus: De Medicina. with an English Translation by W. G. Spencer},
  number           = {292, 304, 336},
  series           = {Loeb Classical Library},
  volumes          = {3}
}
```

Oxyear abbreviates the second year.  But I think it abbreviates too much:

![image](https://user-images.githubusercontent.com/762246/225402310-7fdc7a45-2917-4ffb-8d2a-5ea4d8262ef6.png)

Is there a way to tell Oxyear to say `1935-38`  or `1935-1938`?

**Comment by alex-ball** [comment]
This way of compressing years is the intended behaviour (as seen in, for example, section 15.2.6 of the 2003 Oxford Guide Style), except for legal entries (which compress like 1935–38).

The command that does it is `\blx@ox@compyear`. You could renew it so that the later year is always at least two digits:

```latex
\makeatletter %%% if in document file
\renewcommand{\blx@ox@compyear}[2]{%
  \def\num@one{#1}%
  \def\num@two{#2}%
  \StrLen{\num@one}[\num@one@len]%
  \StrLen{\num@two}[\num@two@len]%
  \ifboolexpr{
    test {\ifnumequal{\num@one@len}{\num@two@len}}
    and
    test {\ifnumless{\num@one}{\num@two}}
  }{%
    \StrCompare{\num@one}{\num@two}[\Result]%
    \ifnum\num@two@len>3%
      \IfStrEq{\Result}{2}{\def\Result{1}}{}%
    \fi
    %%% Extend the legal date compression behaviour to all entries
    \IfStrEq{\Result}{4}{\def\Result{3}}{}%
    %%% End of changes
    \StrGobbleLeft{0\num@two}{\Result}%
  }{\num@two}}
\makeatother %%% if in document file
```

(When you are reading this, note that the later year is padded with a zero on the left before being trimmed, so that at least one digit is always gobbled and hence `\Result` is one more than the net number of digits removed.)

**Comment by wujastyk** [comment]
I'm very grateful!  I do understand that OxRef is Hart-compliant :-)  Thank you for the renewcommand.  I'd never have worked that out.
