### ISSUE TITLE
Commas incorrectly appearing in author-year citations

### ISSUE THREAD

**Issue by ciandorr** [alex-ball/biblatex-oxref#3]
I found that with \usepackage[style=oxyear]{biblatex}, a simple \paencite{key} of an entry where the year field is defined would produce (Author, Year) instead of the desired (Author Year).  After a little research, I was able to fix this by adding the following code to the document preamble, using a new biblatex test introduced in biblatex 3.8:

```
\DeclareDelimFormat{nameyeardelim}{%
      \iflabeldateisdate%
        {\space}%
        {\addcomma\addspace}}
``` 
I don't understand why the old code, using ```\iffieldundef```, didn't produce the same result as this, but I thought I'd share this fix.

**Comment by alex-ball** [comment]
Good catch, thank you for spotting.

The reason why the old code doesn't work is that it is looking for a field called `\thefield{labeldatesource}year`, but when the year string comes from `year` rather than `date`, this expands to `yearyear`.

Your solution is much better, but `\iflabeldateisdate` only tests for `date` and `year`, not `origdate` or `eventdate` which can also provide the year string. I have therefore improved my `\iflabeldateisanydate` macro and used that instead. I've also added some tests to make sure the error does not recur.
