### ISSUE TITLE
Improve citepages support

### ISSUE THREAD

**Issue by moewew** [alex-ball/biblatex-oxref#8]
Via https://tex.stackexchange.com/q/475576/35864

Since `biblatex-oxref`'s `oxnotes` style is built on `verbose.cbx` it also supports its `citepages` option.
Yet it seems to me that `oxnotes` also has additional code to emulate what `citepages=separate` would do in the `.bbx` (!) file

https://github.com/alex-ball/biblatex-oxref/blob/2776e890c0f94fbc21df585f220060e205816352/oxref.dtx#L12612-L12619

Consider the following MWE
```latex
\documentclass{article}

\usepackage[style=oxnotes]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem\footcite[3860-3861]{herrmann}

Ipsum\footcite[lorem]{herrmann}

\citereset Dolor\footcite[lorem]{herrmann}

Sit\footcite[3860-3861]{herrmann}

\printbibliography
\end{document}
```
which gives (only the last bits)

> 3859–62 at 3860–1.
>  at lorem.
> 3859–62 at lorem.
>  at 3860–1.

Using `citepages=separate` only changes one comma in the output.

It seems to me that `oxnotes` could benefit from setting `citepages=separate` as its default and not modifying the `postnote` macro directly. That would make the style slightly more flexible for users since they can use the `citepages` option as expected.
```latex
\documentclass{article}

\usepackage[style=oxnotes, citepages=separate]{biblatex}

\renewbibmacro*{postnote}{%
  \iffieldundef{postnote}
    {}
    {\setunit{\printdelim{postnotedelim}}%
     \printfield{postnote}}}

\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem\footcite[3860-3861]{herrmann}

Ipsum\footcite[lorem]{herrmann}

\citereset Dolor\footcite[lorem]{herrmann}

Sit\footcite[3860-3861]{herrmann}

\printbibliography
\end{document}
```

**Comment by alex-ball** [comment]
Blimey, people really are using it.

> Yet it seems to me that `oxnotes` also has additional code to emulate what `citepages=separate` would do in the `.bbx` (!) file

Yes. I must confess that the citepages option had escaped my attention.

Now the reason it is in the bbx file is a Dirty Hack. This was to allow people to switch freely to a different verbose variant and still have the correct formatting in those circumstances, which was possible because I didn't really need to change anything from the defaults in `verbose.cbx` and friends other than that.

Pre-defining a different `cite:postnote:pages` macro (to remove the comma) and setting `citepages=separate` would be a much better solution, but it does mean that if I want to give people the option of the other verbose variants, I'm going to have to create custom versions of them all. (Or create an option to switch in the unique code from each, which from a maintenance perspective sounds a bad idea.)

Leave it with me.
